In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/Users/nirajkumarpal/Desktop/Machine_Learning/Datasets/play_tennis.csv')

In [3]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df = df.drop(columns=['day'])

In [8]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

# Problem 1

# Outlook=summy, Temp=Hot , Humidity=High, Wind=Weak
# Play or No Play?

# Solution 

# P(yes/sunny,hot,high,weak)=P(sunny/yes) * P(hot/yes) * P(High/yes) * P(weak/yes)

# P(Nos/sunny,hot,high,weak)=P(sunny/No) * P(hot/No) * P(High/No) * P(weak/No)

In [16]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [23]:
Py = 9/14

Pn = 5/14

In [27]:
print(Py)
print(Pn)

0.6428571428571429
0.35714285714285715

In [13]:
# outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [29]:
Pon = 0
Prn = 2/5
Psn = 3/5


Poy = 4/9
Pry = 3/9
Psy = 2/9

In [30]:
# temp

pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [31]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [33]:
# Humidity

pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [34]:
PHighNO=4/5
PNormalN0=1/5


PHighYes=3/9
PNormalYes=6/9

In [35]:
#wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [36]:
PStrongNo=3/5
PWeakNo=2/5

PStrongYes=3/9
PWeakYes=6/9

In [37]:
# Outlook=summy, Temp=Hot , Humidity=High, Wind=Weak

pyes = Py*Psy*PHotYes*PHighYes*PWeakYes
print(pyes)

0.007054673721340388

In [39]:
pno = Pn*Psn*PHotNo*PHighNO*PWeakNo
print(pno)

0.02742857142857143

In [ ]:
# Result = No Play